import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const adSenseId = process.env.GOOGLE_ADSENSE_ID || ""; // 기본값 설정 (선택 사항)

  return (
    <html lang="ko">
      <head>
        <script
          async
          src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${adSenseId}`}
          crossorigin="anonymous"
        ></script>
      </head>
      <body className={inter.className}>
        <div className="flex flex-col min-h-screen bg-gray-100 items-center">
          <Header />
          <main className="flex-1 container px-4">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
